# Generated by Django 4.2.23 on 2026-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
