# Generated by Django 6.0.6 on 2026-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_remove_borrowrecord_status_borrowrecord_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
